# KITTI Object Detection Configuration

# Dataset Configuration
dataset:
  name: "kitti"
  root_dir: "data/kitti"
  train_split: "training"
  val_split: "testing"
  classes: ["Car", "Van", "Truck", "Pedestrian", "Person_sitting", "Cyclist", "Tram", "Misc"]
  img_size: [640, 640]  # YOLOv8 input size
  
# Model Configuration
model:
  name: "yolov8n"  # yolov8n, yolov8s, yolov8m, yolov8l, yolov8x
  pretrained: true
  num_classes: 8

# Training Configuration
training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3
  save_period: 10
  patience: 50  # early stopping patience
  
# Data Augmentation
augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0

# Paths
paths:
  weights_dir: "weights"
  logs_dir: "logs"
  results_dir: "results"
  
# Inference
inference:
  confidence_threshold: 0.25
  iou_threshold: 0.45
  max_detections: 1000